spring:
  application:
    name: aipay
  profiles:
    active: localtest
    
  
  
---
spring:
  profiles: localtest
  freemarker:
    suffix: .ftl
  template-loader-path: classpath:/templates/

server:
  port: 9001
 
 #支付宝支付
alipay:
  app_id: 2016091900544135
  #商户私钥，您的PKCS8格式RSA2私钥
  merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCxxN9wexH+7SvX5MluKfFUbDz7jD7J/rdilTPdbhHLeoqMG9NZUIrtWzOKR/VXuKUUbOsL2OVWgWw//mlCPB+WxBQZ6S+MABBPgv6B5UHnQsfJGoP/Tl3sr/sr828Hq5ZDy2IZfnLKdYIfISq/dlWwbYVIqKoxajJ+ulj8np5pJ6GVhYgxOZHNEEmapU0TPepc34m7u9lXZxAZf2/6kKcgcmQvvMsCFUo2LKZUo2aR56YvnaCrSiw+ZpnH4fpN2om3mVqny0PZcDcnDUKQ8gbJ0STmd0VGV2zDw4B4PakGaorwy5rS4DsL8pQ2qeUosozfXIIRCUag6GJgfvNM5rK5AgMBAAECggEAFzuIjBW5e1yZr0R6Qsh+fq8KpUFl71Y3t02SkqzQ7IveUYNNcs3A6lZR/Q98c/Nwt6OocErvZgfSEub38K0U38pOajh8e0qC1zFie61vmH60x4aMm7AtPEKfi9Xru8/j+oY5EuXgsK78y361LIKVnlIh6iYI4B5l7QQDnzhHsaxBBJ1Uxy3rQ9cey64gTRCZ1zlS/tfAHskuzaBCy4sZFGqupXExU+tNVzL/fIpinZaeUixzkX5JMl3+E4Mis2oRqNdCQ3fOMLgTNoMb6GlT3ttEbq7lpmWl49UeJAQ5TY6sjySQ2+Qh58FGVIdw7B/jNbzyh05fBVqMa3Mn5BubdQKBgQDzkTqx9MMBJepSNgHDKP6lXNmnS17+eUFw9cdIM4FxF6kLuMkVMPMN1OjnNlG1Sln/Ffmqqcy6WPbohwWeyKt5yvVNZVV1RZsot3GUAn29aVQdaFpNrXAndDJp82yZuLYGENjF0BGgP3BxVntzmOWAH+VtEXspB50cEBeomXdswwKBgQC619Y6Uch6TZbO/THuTocn1WVu8UgsPV1ROXJhtV5HahUkdDT+ruRT6uTMX4LTUu8frc61xpzlwbaTd//y86koKshdKUqgn00+D8Yr7PTcbPpYdrDZMPhb1TNbSiIrUO8ReoBTsncnwlc2hMmVl08OrAhVwqTpRXAqIPPKSh7a0wKBgQDeG7qNmyjUfDHQ5ET5JgII48HrR9UJc6OUkdw3YBiS+8OA1/Iuq+OI4nW8mpEqI/Irpmt1EMCL0iLeanpakJ2mQ8kr2dNzTJUwLRCaqybkug8lfgqTOSzEHbb3XS7Ug1ch8uzqflIEcrVj9TxAbtYh33RE4KMSCEph097vNXttJwKBgCmFdZIYQpkLTQxKsCHpSZfMkHILJKLQMECwp36XM5BjPrePK4e9jfgoJxhT0Vrs/z7m/RzgOlXEqrIy5Ko1A85tU4GAf5kaTawRDVUNn4ysmyW1mq9pdofR5UvQOa+umLIlqwbujhRD1+XBtJqNuX/lMyT70HIWgEqccBDwT9MJAoGAXIZOg111CnwMH9slVBAxd8Jx4fEUgem+XdXkSOJk6LrXaOtSzyisQwSxK5yTELd+LY/NP5tWRjWgMDp2YOOVndBPxgSUC0PK7PX+TrwABijDslPQhFCO41ns+pozD7rj4r+NncmfBAZe1cC0c6LjlxilBTiTIRUST5tScmDU9bI=
  #支付宝公钥
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtPIjoM1PdKGqhKHIohvNBHcYxPNXtHJa1eg6iavpIj3hVfv4VhDjH8NDuB29r+0T1aRdTG+TMjG2pZry/VRiDyEsMQRZPlms3NMUDEHiKZoZiVq+A7uHyXd9x7b81UVueyYrO24Eta7n247kItC+ZvXhoL48Db1+3qFt4MuJ9bZeTo7EhUcl/gF8dfJ70g7ALiFFTA4yMC6h76BtFtyyj8KUpcKOYQfmd5Thcbhjlz8q+ePP8knseJxJHfZl38yvlhM/NrVk9TLZC8xfBNXXjvShsOL74T93k7R8vQ/VjrSaF6eR+Wd/FV2v2Dn2WT5TZfJcDme0A/+RgWg+J2SROQIDAQAB
  #服务器异步通知页面路径处理逻辑
  notify_url: http://47.98.142.153:9001/rest/alipay/pay
  #页面跳转同步通知页面路径返回商户页面
  return_url: http://47.98.142.153:9001/rest/alipay/payNotify
  #签名方式
  sign_type: RSA2
  #字符编码格式
  charset: utf-8
  #支付宝网关
  gatewayUrl: https://openapi.alipaydev.com/gateway.do
  #付款方
  payer_show_name: 测试买家





---
spring:
  profiles: test
  
server:
  port: 9002